### ISSUE TITLE
[FEAT] 광고 시청 후 포인트 획득하기

### ISSUE THREAD

**Issue by alveloper** [team-mokcha/corabal-beta#10]
## 📔   개요
1. 프로필 스크린, 샵 스크린에서 유저는 보상형 비디오 광고를 시청할 수 있습니다.
2. 광고를 시청한 유저는 5 포인트를 얻을 수 있습니다.

## ✅    작업 사항

백엔드
- [ ] 유저가 광고를 시청할 때, 시청한 날의 watched_ad_counts 수를 +1 (최대 3)
- [ ] watched_ad_counts 의 수가 3을 초과할 경우 에러 발생
- [ ] 포인트 watched_ADs, current 에 watched_ad_counts 수만큼 +5

프론트엔드
- [x] 프로필 스크린, 샵 스크린에 포인트 확인하는 레이아웃 구현
- [x] DB에서 포인트(current) 가져와서 보여주기
- [x] 광고 보기 버튼을 클릭했을 때 전면 광고가 뜨도록 하기

## ⛑️    참고 사항
react native admob 라이브러리 사용 예정 ([참고 링크](https://dev-yakuza.posstree.com/ko/react-native/react-native-admob/))

**Comment by alveloper** [comment]
![image](https://user-images.githubusercontent.com/73899253/133924594-f9176ce0-93c6-4766-9bb7-5a339ffcca70.png)

**Comment by alveloper** [comment]
https://medium.com/geekculture/google-admob-for-react-native-via-firebase-11a2a6fa555a

**Comment by alveloper** [comment]
> https://medium.com/geekculture/google-admob-for-react-native-via-firebase-11a2a6fa555a

- 대부분의 튜토리얼이 "react native 와 firebase, admob 을 함께 쓰기 위해선 [react native firebase](https://rnfirebase.io/)를 설치하라"고 함
- 실제로 설치해서 테스트 해봤을 때, 해당 기능은 구 버전의 react native firebase 라서 실행도 제대로 되지 않고 앞으로 지원이 가능할지도 미지수인 상태임 https://github.com/invertase/react-native-firebase/issues/5329#issue-894056954
- 파이어베이스 공식문서에선 안드로이드 앱을 만들기 위해서 코틀린만 사용하는 걸로 나와있음...

**Comment by alveloper** [comment]
[async await try catch + typescript](https://blog.logrocket.com/async-await-in-typescript/)

**Comment by alveloper** [comment]
백엔드 로직 짜는 중에 다음과 같은 에러 발생
```
[Unhandled promise rejection: FirebaseError: Missing or insufficient permissions.]
at node_modules\@babel\runtime\helpers\construct.js:22:9 in _construct        
at node_modules\@babel\runtime\helpers\wrapNativeSuper.js:26:22 in Wrapper    
at node_modules\@firebase\webchannel-wrapper\dist\index.js:37:143 in Ab       
at node_modules\@firebase\webchannel-wrapper\dist\index.js:42:590 in <anonymous>
at node_modules\@firebase\firestore\dist\rn\prebuilt.rn-f9cd27ba.js:2326:9 in 
ue
at node_modules\@firebase\firestore\dist\rn\prebuilt.rn-f9cd27ba.js:2327:5 in 
<global>
at node_modules\@firebase\firestore\dist\rn\prebuilt.rn-f9cd27ba.js:5854:0 in 
<anonymous>
at node_modules\@firebase\firestore\dist\rn\prebuilt.rn-f9cd27ba.js:5819:27 in Ho.Si.next$argument_0
at node_modules\@firebase\firestore\dist\rn\prebuilt.rn-f9cd27ba.js:5838:19 in <anonymous>
at node_modules\@firebase\firestore\dist\rn\prebuilt.rn-f9cd27ba.js:10172:17 in Oc#r_
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 
in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass      
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates    
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0  
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue   
```
우선 파이어스토어 규칙을 다음과 같이 수정해서 테스트 중임
```
// 개발 단계에선 우선 아래 룰 적용 중임.
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

**Comment by alveloper** [comment]
해야 할 일
- [ ] 유저가 오늘 접속해서 date 컬렉션에 오늘 날짜의 다큐먼트가 없으면 생성해야 함 -> 혜진님 파트랑 겹치는지 확인해보기
- [ ] 다큐먼트 조회할 때 자꾸 undefined 뜨는 이유 알아보기
- [ ] 위에서 나왔던 파이어스토어도 알아보기
